"""oauth db update

Revision ID: 2b6db228d3ab
Revises: 1034f2fc349e
Create Date: 2025-09-23 11:16:04.561874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6db228d3ab'
down_revision: Union[str, Sequence[str], None] = '1034f2fc349e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.VARCHAR(length=50), server_default='local', nullable=False))
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(length=255), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
